[profile.default]
src = "src"
out = "out"
libs = ["lib"]

remappings = [
  "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
  "@chainlink/contracts/=lib/chainlink-brownie-contracts/contracts/"
]

solc_version = "0.8.29"

fs_permissions = [ { access = "read", path = "./functionsSource" } ]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
